// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: incident/v1alpha3/types.proto

package v1alpha3

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The "Syntax" is the tooling that should be used to convert the content to a consumable format.
type Text_Syntax int32

const (
	Text_PLAIN_TEXT Text_Syntax = 0
	Text_MARKDOWN   Text_Syntax = 1
	Text_ASCIIDOC   Text_Syntax = 2
)

// Enum value maps for Text_Syntax.
var (
	Text_Syntax_name = map[int32]string{
		0: "PLAIN_TEXT",
		1: "MARKDOWN",
		2: "ASCIIDOC",
	}
	Text_Syntax_value = map[string]int32{
		"PLAIN_TEXT": 0,
		"MARKDOWN":   1,
		"ASCIIDOC":   2,
	}
)

func (x Text_Syntax) Enum() *Text_Syntax {
	p := new(Text_Syntax)
	*p = x
	return p
}

func (x Text_Syntax) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Text_Syntax) Descriptor() protoreflect.EnumDescriptor {
	return file_incident_v1alpha3_types_proto_enumTypes[0].Descriptor()
}

func (Text_Syntax) Type() protoreflect.EnumType {
	return &file_incident_v1alpha3_types_proto_enumTypes[0]
}

func (x Text_Syntax) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Text_Syntax.Descriptor instead.
func (Text_Syntax) EnumDescriptor() ([]byte, []int) {
	return file_incident_v1alpha3_types_proto_rawDescGZIP(), []int{3, 0}
}

// Incident is:
// >  An occurrence that actually or potentially jeopardizes the confidentiality, integrity, or availability of an
// >  information system or the information the system processes, stores, or transmits or that constitutes a violation
// >  or imminent threat of violation of security policies, security procedures, or acceptable use policies.
// >
//         — https://csrc.nist.gov/glossary/term/incident
//
// An incident is started when the first impact is identified, and concluded with all identified impacts have been
// mitigated, such that users are no longer affected outside the error margin (i.e. outside SLOs).
type Incident struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Should be a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier)
	// Example: e1da1be2-eff2-11e8-a204-0f0dc88152cb
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The identified undesired consequences of this anomaly.
	Impacts []*Impact `protobuf:"bytes,2,rep,name=impacts,proto3" json:"impacts,omitempty"`
}

func (x *Incident) Reset() {
	*x = Incident{}
	if protoimpl.UnsafeEnabled {
		mi := &file_incident_v1alpha3_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_incident_v1alpha3_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_incident_v1alpha3_types_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetImpacts() []*Impact {
	if x != nil {
		return x.Impacts
	}
	return nil
}

// An "Impact" is some undesirable consequence or outcome as a result of the incident.
type Impact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Should be a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier)
	// Example: e1da1be2-eff2-11e8-a204-0f0dc88152cb
	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timeline []*Event `protobuf:"bytes,2,rep,name=timeline,proto3" json:"timeline,omitempty"`
}

func (x *Impact) Reset() {
	*x = Impact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_incident_v1alpha3_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Impact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Impact) ProtoMessage() {}

func (x *Impact) ProtoReflect() protoreflect.Message {
	mi := &file_incident_v1alpha3_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Impact.ProtoReflect.Descriptor instead.
func (*Impact) Descriptor() ([]byte, []int) {
	return file_incident_v1alpha3_types_proto_rawDescGZIP(), []int{1}
}

func (x *Impact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Impact) GetTimeline() []*Event {
	if x != nil {
		return x.Timeline
	}
	return nil
}

// An "event" is a notable occurrance that happened during an incident
//
// Fundamentally an Event is "thing" — just something of note that happened during the incident itself, or even before &
// after.
//
// The "Incident" lasts a long as the impacts exist.
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Should be a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier)
	// Example: e1da1be2-eff2-11e8-a204-0f0dc88152cb
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The point at which the event occurred
	Timestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// A free text description of a given event.
	Description *Text `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// A set of free tags associated this event to group and categories timeline entries.
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_incident_v1alpha3_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_incident_v1alpha3_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_incident_v1alpha3_types_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetDescription() *Text {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Event) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// "Text" is a field type which is essentially a "free text" field, flavoured with a particular markup type.
type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The syntax used in this text area
	Syntax Text_Syntax `protobuf:"varint,1,opt,name=syntax,proto3,enum=v1alpha3.Text_Syntax" json:"syntax,omitempty"`
	// The content of this text area
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_incident_v1alpha3_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_incident_v1alpha3_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_incident_v1alpha3_types_proto_rawDescGZIP(), []int{3}
}

func (x *Text) GetSyntax() Text_Syntax {
	if x != nil {
		return x.Syntax
	}
	return Text_PLAIN_TEXT
}

func (x *Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_incident_v1alpha3_types_proto protoreflect.FileDescriptor

var file_incident_v1alpha3_types_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x33, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x33, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x08, 0x49, 0x6e,
	0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x69, 0x6d, 0x70, 0x61, 0x63, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x33, 0x2e, 0x49, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x52, 0x07, 0x69, 0x6d, 0x70, 0x61, 0x63,
	0x74, 0x73, 0x22, 0x45, 0x0a, 0x06, 0x49, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x08,
	0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x33, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x05, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x30, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x33, 0x2e, 0x54, 0x65,
	0x78, 0x74, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2d, 0x0a, 0x06,
	0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x33, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x53, 0x79, 0x6e,
	0x74, 0x61, 0x78, 0x52, 0x06, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x12,
	0x0e, 0x0a, 0x0a, 0x50, 0x4c, 0x41, 0x49, 0x4e, 0x5f, 0x54, 0x45, 0x58, 0x54, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x52, 0x4b, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x53, 0x43, 0x49, 0x49, 0x44, 0x4f, 0x43, 0x10, 0x02, 0x42, 0x2b, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x68, 0x73, 0x68, 0x74, 0x69,
	0x6f, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x63, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_incident_v1alpha3_types_proto_rawDescOnce sync.Once
	file_incident_v1alpha3_types_proto_rawDescData = file_incident_v1alpha3_types_proto_rawDesc
)

func file_incident_v1alpha3_types_proto_rawDescGZIP() []byte {
	file_incident_v1alpha3_types_proto_rawDescOnce.Do(func() {
		file_incident_v1alpha3_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_incident_v1alpha3_types_proto_rawDescData)
	})
	return file_incident_v1alpha3_types_proto_rawDescData
}

var file_incident_v1alpha3_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_incident_v1alpha3_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_incident_v1alpha3_types_proto_goTypes = []interface{}{
	(Text_Syntax)(0),            // 0: v1alpha3.Text.Syntax
	(*Incident)(nil),            // 1: v1alpha3.Incident
	(*Impact)(nil),              // 2: v1alpha3.Impact
	(*Event)(nil),               // 3: v1alpha3.Event
	(*Text)(nil),                // 4: v1alpha3.Text
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_incident_v1alpha3_types_proto_depIdxs = []int32{
	2, // 0: v1alpha3.Incident.impacts:type_name -> v1alpha3.Impact
	3, // 1: v1alpha3.Impact.timeline:type_name -> v1alpha3.Event
	5, // 2: v1alpha3.Event.timestamp:type_name -> google.protobuf.Timestamp
	4, // 3: v1alpha3.Event.description:type_name -> v1alpha3.Text
	0, // 4: v1alpha3.Text.syntax:type_name -> v1alpha3.Text.Syntax
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_incident_v1alpha3_types_proto_init() }
func file_incident_v1alpha3_types_proto_init() {
	if File_incident_v1alpha3_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_incident_v1alpha3_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Incident); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_incident_v1alpha3_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Impact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_incident_v1alpha3_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_incident_v1alpha3_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_incident_v1alpha3_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_incident_v1alpha3_types_proto_goTypes,
		DependencyIndexes: file_incident_v1alpha3_types_proto_depIdxs,
		EnumInfos:         file_incident_v1alpha3_types_proto_enumTypes,
		MessageInfos:      file_incident_v1alpha3_types_proto_msgTypes,
	}.Build()
	File_incident_v1alpha3_types_proto = out.File
	file_incident_v1alpha3_types_proto_rawDesc = nil
	file_incident_v1alpha3_types_proto_goTypes = nil
	file_incident_v1alpha3_types_proto_depIdxs = nil
}
